baseURL = "https://mgmtconfig.com/"
languageCode = "en-ca"
title = "Mgmt Config"
theme = "hugo-serif-theme"
#themesDir = "themes/"

[params]
	# In most cases you will only want to use either one of these. If you
	# have Google Analytics included in your GTM tags don't put your GA ID
	# here. Otherwise your data might be useless.
	google_analytics_id = ""
	google_tag_manager_id = ""

	# Used by purpleidea to display a url string visually.
	shortURL = "mgmtconfig.com"
	# Site title
	title = "Mgmt Config - Fast, Real-time, Closed-Loop Automation"

	publickeyfile = "static/james@shubin.ca.asc"

[params.logo]
	mobile = "images/mgmt_logo_default_symbol.svg"	# TODO: do we need to optimize here?
	standard  = "images/mgmt_logo_default_symbol.svg"
	#standard  = "images/mgmt_logo_default_wide.svg"
	alt = "Mgmt Config - Fast, Real-time, Closed-Loop Automation."

[params.homepage_meta_tags]
	meta_description = "Mgmt Config - Fast, Real-time, Closed-Loop Automation."
	meta_og_title = "Mgmt Config"
	meta_og_type = "website"
	meta_og_url = "https://mgmtconfig.com/"
	# I think this is used in URL's and stuff when someone needs a thumbnail.
	#meta_og_image = "https://mgmtconfig.com/images/tn.png" # TODO: do we need this?
	meta_og_description = "Mgmt Config - Fast, Real-time, Closed-Loop Automation."
	meta_twitter_card = "summary"
	meta_twitter_site = "@mgmtconfig"
	meta_twitter_creator = "@purpleidea"

[menu]
	# Main Menu
	[[menu.main]]
		name = "Services"
		url = "/services/"
		weight = 1

        [[menu.main]]
                name = "Docs"
                url = "/docs/"
                weight = 1

	#[[menu.main]]
	#	name = "Team"
	#	url = "/team/"
	#	weight = 2

	# Footer Menu
	[[menu.footer]]
		name = "Home"
		url = "/"
		weight = 1

	[[menu.footer]]
		name = "Contact"
		url = "/contact/"
		weight = 2
